name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Dokku deploy
        uses: vitalyliber/dokku-github-action@v5.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: dokkugjensidige.norwayeast.cloudapp.azure.com
          PROJECT: gje-quizbot
          FORCE_DEPLOY: true
